### PR TITLE
Downloader nodes

### PR DESCRIPTION
**Pull request by Lenivaya**
# Updates

## Downloader nodes

It&rsquo;s now possible to create nodes which will download resulting data in the browser.

# Implementation details

## DownloaderNode

Simple class that extends default Node type adding one extra property &#x2014; downloadData, which is supposed to be filled by Node on run execution.

## DownloadData

Class that holds:

-   data
-   mimeType of that data
-   fileName
-   fileExtension

This class have pretty generic download method that can be reused among most common cases, so all required work for every specific down-loader node is to specify right data, mimeType and fileName, everything about the downloading will be handled by DownloadData.

Class also supports generics so it&rsquo;s possible to specify type of the Data downloaded, for now ti just any

```js
this.downloadData = new DownloadData<any>({
    data: [],
    mimeType: 'application/json',
    fileName: fileName,
    fileExtension: 'json',
});
```

## Diagram run 

To check what nodes are supposed to run with Diagram run method, we are simply doing a couple of checks

```js
if (
    // Check of whether node is downloader
    node instanceof DownloaderNode &&
    // Check of whether code runs in browser
    // environment
    (isBrowser || isJsDom)
) {
    await node.downloadData.download();
}
```

## DownloadJSON node

Can be ran with dot-notated paths, so if we for example specify ***title*** as an attribute to download, we will get only those attributes from all features. Filename will be in such format
```js
[node_name] [date_downloaded].json
```

# Example of usage
2021-08-28-20:53:43_compressed

### CODE REVIEW

**Comment by Lenivaya** [comment]
Things need to be added/fixed/considered
## Tests
Find a good way of testing downloader nodes. Possibly it might be testing of right DownloadData creation for the nodes in the core, and e2e tests for the download functionality in the gui
## Downloading in headless mode
For now downloading functionality works only when code runs in the browser environment, it may be good feature to add separate downloading cases for both browser and node environment. So in node environment download will save data to some cross-platform data folder like **dataDir/data-story/filename_date.json**

**Review by ajthinking — COMMENTED** [review]
* Nice, you bet me to it. Works great in chrome!
* Possibly, method `DownloadData.download` can be implemented in gui as a callback or similar instead since it is so heavily involved with browser (document, createElement etc) ? I see we have a guard clause to see if it is running in browser environment, but anyways might be a good separation to make
* gui/`"file-saver": "^2.0.5",` - this can be removed. Nice to implement this without a package 👌 
* Add pretty print option on json
* When handling dot notation, we can make use of Obj.get helper

> Find a good way of testing downloader nodes

Might be another reason to move the actual downloading part to gui?

> So in node environment download will save data to some cross-platform data folder like dataDir/data-story/filename_date.json

Great idea :thumb_up:

**Comment by Lenivaya** [comment]
>  Possibly, method DownloadData.download can be implemented in gui as a callback or similar instead since it is so heavily involved with browser (document, createElement etc) ? I see we have a guard clause to see if it is running in browser environment, but anyways might be a good separation to make

That's how I started implementing it at first, but that approach will require extra actions looping through the node list and applying callback on the gui side, so I decided to do all things in one place with just environment checking.

>  gui/"file-saver": "^2.0.5", - this can be removed. Nice to implement this without a package

Yes, current solution works pretty nice, though it may be a good idea to take a look on [StreamSaver](https://github.com/jimmywarting/StreamSaver.js), which can handle bigger files creation asynchronously using streams directly to the file-system

> Add pretty print option on json

I think that this must be an option in form of select parameter in DownloadJSON node, so user can choose whether he want's to format downloaded data or not. 

> When handling dot notation, we can make use of Obj.get helper

Yeah, it handles just what I've done manually, feels like nice possibility to decrease code verbosity 

> Might be another reason to move the actual downloading part to gui?

The problem here is by moving download function to the gui we'll still have to create the same testing workflow as with download isolated at the DataStory class in the core. So still e2e tests of downloading functionality in gui and  tests of right data creation in core.

**Comment by Lenivaya** [comment]
# Updates
It's now possible to specify multiple attributes which then will be downloaded, so for example if we had such a config for a DownloadJSON node

image

We would get all attributes we specified downloaded
image

**Comment by ajthinking** [comment]
> That's how I started implementing it at first, but that approach will require extra actions looping through the node list and applying callback on the gui side, so I decided to do all things in one place with just environment checking.

Ok that makes sense, lets keep it in core 👍

**Review by ajthinking — APPROVED** [review]

**Pull request merged**
