### PR TITLE
Upgrade CI

### PR DESCRIPTION
**Pull request by Lenivaya**
# Prerequisites
To facilitate some time-consuming development steps, the great idea would be to put them on cloud computing.
## Code linting and formatting
Instead of constantly formatting and searching for the style errors in our code, we will use github actions. For every commit we can have automatic formatting, fixing errors by and information about warnings by eslint. (Latest commit shows automatic adding of semicolon)
## Pull-request dependencies
It's also pretty convenient to have information about what dependencies were changed or added by pull-request. This workflow will give us usable info about that.
## Automatic issues
Since the project is in active development it would be useful to create issues automatically. There are also plugins for almost every IDE to search and manage TODO's. That workflow gives us the ability to convert "TODO" entries into issues. For example the following piece of code
```js
  // TODO Implement run() for the Comment class
  async run() {
    return null;
  }
```
Will be converted to an issue with the name "Implement run() for the Comment class", which will include a link to the TODO in code.
## Dependencies updates
Denepdabot will try to search for updates and will create a PR if there are any.

### CODE REVIEW

**Comment by ajthinking** [comment]
Wow, _very_ cool!

> Apply formatting changes

Nice, so it only does this on touched code? If for some reason I should want custom style, can I decline it? I guess It is easiest for me to just do PR and see how this works. Happy to merge this!

**Comment by Lenivaya** [comment]
> Nice, so it only does this on touched code? If for some reason I should want custom style, can I decline it? I guess It is easiest for me to just do PR and see how this works.

You can always disable prettier for specific files if you want to, but usually it gives very readable and comfortable result (can be configured according to your preferences as well)

> Is this fixable?
> 
> ```
> Run wearerequired/lint-action@v1
> Error: This action does not have permission to create annotations on forks. You may want to run it only on `push` events. See https://github.com/wearerequired/lint-action/issues/13 for details
> Adding "Lenivaya/core" fork as remote with Git
> Fetching remote branch "master"
> From https://github.com/Lenivaya/core
>  * branch            master     -> FETCH_HEAD
>  * [new branch]      master     -> fork/master
> Switching to the "master" branch
> Previous HEAD position was 7808d3f Merge 9be6f5d6aea6ed1a72ae5f793db27b168972084a into 25abe2c831953687c69fafe890fe09642fa4116d
> Switched to branch 'master'
> SHA of last commit is "9be6f5d6aea6ed1a72ae5f793db27b168972084a"
> Run ESLint
> Create check runs with commit annotations
>   There are more than 50 errors/warnings from ESLint. Annotations are created for the first 50 issues only.
>   Creating GitHub check with 50 annotations for ESLint…
>   Error: Error: Received status code 403
>   Error: Error trying to create GitHub check for ESLint: Received status code 403
> ```

That's appears because I'm not the owner of the repo, all must work as it should after being merged(you can make sure by checking run summary on my fork - https://github.com/Lenivaya/core/actions/runs/1023207391)

**Comment by ajthinking** [comment]
> You can always disable prettier for specific files if you want to, but usually it gives very readable and comfortable result (can be configured according to your preferences as well)

Lot of times I like it to stack, like this:
```js
it('can build diagrams programatically', () => {
  expect(DiagramBuilder.begin()
    .add(Create)
    .add(Inspect)
    .finish())
    .toBeInstanceOf(Diagram);
});
```

Rather than

```js
it('can build diagrams programatically', () => {
  expect(DiagramBuilder.begin().add(Create).add(Inspect).finish()).toBeInstanceOf(Diagram);
});
```

That goes for all tests, probably elsewhere as well. What do you recommend to allow for that?

> That's appears because I'm not the owner of the repo, all must work as it should after being merged(you can make sure by checking run summary on my fork - https://github.com/Lenivaya/core/actions/runs/1023207391)

Perfect!

**Comment by Lenivaya** [comment]
> Rather than
> 
> ```js
> it('can build diagrams programatically', () => {
>   expect(DiagramBuilder.begin().add(Create).add(Inspect).finish()).toBeInstanceOf(Diagram);
> });
> ```

I can agree it's looking strange, but it seems like I found out why prettier format like this. Author of boilerplate from which you created project for somewhat reasons decided to increase "printWidth" in prettier config up to 120 characters. By decreasing this number in two times I got this code formatted like on the screenshot
screenshot-EMhq7a

Now it's looks much nicer

**Comment by ajthinking** [comment]
> Now it looks much nicer

Perfect!

**Pull request merged**
