### PR TITLE
Add FilterNode

### PR DESCRIPTION
**Pull request by ajthinking**
Needs [gui/104](https://github.com/data-story-org/gui/pull/106)

### CODE REVIEW

**Comment by Lenivaya** [comment]
# Updates
# Filter node
filters against configured attribute and output ports, all unmatched features wil be passed as output
# Examples of usage
For example let's take diagram with such view and starting json

image
Screenshot 2021-08-09 at 13-24-28 DataStory

Filter is configured to match against status, output ports are:
- upcoming
- sold

Screenshot 2021-08-09 at 14-58-31 DataStory

After running the story we can see that filtering works as expected, for sold and upcoming we have

Screenshot 2021-08-09 at 14-59-07 DataStory
Screenshot 2021-08-09 at 14-59-20 DataStory

And for the unmatched we have for-sale, which wasn't configured as output port

Screenshot 2021-08-09 at 14-59-30 DataStory

# Problems
## Tests
For some reasons test-suite reports that Diagram or features are undefined. It seems like it need some helper to create output ports like we do this in gui.

**Comment by Lenivaya** [comment]
# Another working example 
Here is another example, we filtering features returned by httpRequest by tittle attribute(because every title is unique), as screenshot shows, after filtering we have one matched and 199 unmatched features(exactly as expected)

Screenshot 2021-08-09 at 15-21-13 DataStory

**Comment by ajthinking** [comment]
Looks great! 

> For some reasons test-suite reports that Diagram or features are undefined. It seems like it need some helper to create output ports like we do this in gui.

I think so far only used the NodeTester class on simple Input/Output nodes. Might be a bug when there are more ports? Another thing to look into is if the ports live in node.options or directly on the node - might need some refactors there.

<hr>

How about renaming Output -> Unfiltered ?

Feel free to continue this and the other pr in gui, let me know if you need feedback

**Comment by Lenivaya** [comment]
> How about renaming Output -> Unfiltered ?

That exactly how I firstly implemented it, but that needs some further upgrades in testing functionality

**Comment by ajthinking** [comment]
> That exactly how I firstly implemented it, but that needs some further upgrades in testing functionality

Got it

**Comment by ajthinking** [comment]
Also that would need being more explicit in the assert, something like:
```
.assertOutputs({Unfiltered: [...])
```
Though as a I understand theres another error before that

**Comment by Lenivaya** [comment]
# Updates
- now all fieldTypes are strictly typed, so better error handling and completion in IDE's
- field are divided into two main groups, simple and complex(high-order) which can be a wrapper around simple filed types
- new Port fieldType

**Comment by Lenivaya** [comment]
# Updates


## Unconfigured outputs

If user has not configured the output ports, he won&rsquo;t receive any errors


## Dot-notated paths support

If we for example create such a json

```json
[
    {
        "resource": {
            "nested": {
                "value": "for-sold"
            }
        }
    }
]
```

and filter it like on the screenshot

Screenshot 2021-08-15 at 16-02-23 DataStory


we&rsquo;ll receive quite expected results

Screenshot 2021-08-15 at 16-03-54 DataStory
Screenshot 2021-08-15 at 16-04-12 DataStory

**Comment by ajthinking** [comment]
Perfect!

**Comment by Lenivaya** [comment]
# Updates


## Primitive features

Filter now support matching against features generally, will trigger automatically if user don&rsquo;t changed default value, specified either empty attribute to match or explicitly set it to &rsquo;none&rsquo;.


## Example

Let&rsquo;s say for example we create simple string feature with Create node and added value "for-sold". Filtering configuration looks like on the screenshot

Screenshot 2021-08-15 at 20-24-45 DataStory


and after running we get definitely what we expected &#x2014; 1 feature for &rsquo;for-sold&rsquo; output port and 0 features for the &rsquo;Unfiltered&rsquo; port

Screenshot 2021-08-15 at 20-24-35 DataStory
Screenshot 2021-08-15 at 20-25-53 DataStory

**Pull request merged**
